# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e7bb49cd0b658e25ebd4bad98febc3ca564fae8a0e19822bb2250033c0e54afc01b650f2dbb72deef6ecdd3266aef79b45d2a83ecd8f7e00ee95cc9573cc1e7

test:
  secret_key_base: 03b595c7cb3000b4b30c88e1d2e922fe634ed877185b3b55b5399cea8408d3a9876c0d3a06b040b7e058b2459a42aee29ccc39d81562449c3f00b1b75645fba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
